// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/alipay/notify": {
            "post": {
                "tags": [
                    "alipay支付相关接口"
                ],
                "summary": "异步通知",
                "responses": {}
            }
        },
        "/api/v1/integral/generate_key": {
            "post": {
                "tags": [
                    "积分相关接口"
                ],
                "summary": "生成积分充值密钥并发送到指定邮箱",
                "parameters": [
                    {
                        "description": "生成key的请求参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/integral.BatchGenerateKeyRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/integral/manual/recharge": {
            "post": {
                "tags": [
                    "积分相关接口"
                ],
                "summary": "手动充值(管理员使用)",
                "parameters": [
                    {
                        "description": "手动充值请求参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/integral.ManualRechargeRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/integral/recharge": {
            "post": {
                "tags": [
                    "积分相关接口"
                ],
                "summary": "充值",
                "parameters": [
                    {
                        "description": "充值请求参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/integral.RechargeRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/openai/v1/audio": {
            "post": {
                "tags": [
                    "代理OpenAI相关接口"
                ],
                "summary": "音频转文字",
                "parameters": [
                    {
                        "type": "file",
                        "description": "音频文件",
                        "name": "audio",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "model",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "language",
                        "name": "language",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "prompt",
                        "name": "prompt",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "temperature",
                        "name": "temperature",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/openai/v1/chat/completions": {
            "post": {
                "tags": [
                    "代理OpenAI相关接口"
                ],
                "summary": "对话",
                "parameters": [
                    {
                        "description": "openai请求参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/openaiapi.ChatCompletionRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/openai/v1/image": {
            "post": {
                "tags": [
                    "代理OpenAI相关接口"
                ],
                "summary": "生成图片",
                "parameters": [
                    {
                        "description": "openai请求参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/openai.ImageRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/pay/pre_create": {
            "post": {
                "tags": [
                    "支付相关接口"
                ],
                "summary": "预创建交易订单",
                "parameters": [
                    {
                        "description": "订单请求参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payapi.PreCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建订单返回参数",
                        "schema": {
                            "$ref": "#/definitions/payapi.PreCreateResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/pay/status": {
            "get": {
                "tags": [
                    "支付相关接口"
                ],
                "summary": "获取支付状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单id",
                        "name": "orderId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "支付状态：1-待支付,2-已支付,3-已取消",
                        "schema": {
                            "type": "int"
                        }
                    }
                }
            }
        },
        "/api/v1/user/change_password": {
            "post": {
                "tags": [
                    "用户相关接口"
                ],
                "summary": "用户修改密码",
                "parameters": [
                    {
                        "description": "发送验证码请求参数(默认为email)",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/user/change_password/verify/code": {
            "post": {
                "tags": [
                    "用户相关接口"
                ],
                "summary": "在忘记密码时发送验证码",
                "parameters": [
                    {
                        "description": "发送验证码请求参数(默认为email)",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.SendPasswordVerificationCodeRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/user/feedback": {
            "post": {
                "tags": [
                    "用户相关接口"
                ],
                "summary": "意见反馈",
                "parameters": [
                    {
                        "description": "反馈信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.FeedbackRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/user/login": {
            "post": {
                "tags": [
                    "用户相关接口"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录请求参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回token",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/logout": {
            "post": {
                "tags": [
                    "用户相关接口"
                ],
                "summary": "登出",
                "responses": {
                    "200": {
                        "description": "返回token",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/menu": {
            "get": {
                "tags": [
                    "用户相关接口"
                ],
                "summary": "获取主菜单信息",
                "responses": {
                    "200": {
                        "description": "主菜单信息",
                        "schema": {
                            "$ref": "#/definitions/menu.Menu"
                        }
                    }
                }
            }
        },
        "/api/v1/user/profile": {
            "get": {
                "tags": [
                    "用户相关接口"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.ProfileResponse"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "用户相关接口"
                ],
                "summary": "修改用户信息",
                "parameters": [
                    {
                        "description": "用户信息和自定义配置",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ProfileRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/user/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册请求参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回token",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/verify/send_code": {
            "post": {
                "tags": [
                    "用户相关接口"
                ],
                "summary": "发送验证码",
                "parameters": [
                    {
                        "description": "发送验证码请求参数(默认为email)",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.SendVerificationCodeRequest"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "integral.BatchGenerateKeyRequest": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "default": 10
                },
                "type": {
                    "description": "1代表100积分，2代表500积分，3代表2000积分",
                    "type": "integer",
                    "default": 1
                }
            }
        },
        "integral.ManualRechargeRequest": {
            "type": "object",
            "required": [
                "key"
            ],
            "properties": {
                "auth_code": {
                    "description": "允许充值的授权码",
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "to_email": {
                    "type": "string"
                }
            }
        },
        "integral.RechargeRequest": {
            "type": "object",
            "required": [
                "key"
            ],
            "properties": {
                "key": {
                    "type": "string"
                }
            }
        },
        "menu.Item": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "type": {
                    "description": "类型：chat/image/audio",
                    "type": "string"
                }
            }
        },
        "menu.Menu": {
            "type": "object",
            "properties": {
                "tabs": {
                    "description": "菜单tab",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/menu.Tab"
                    }
                }
            }
        },
        "menu.Tab": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "菜单分类：角色/工具",
                    "type": "string"
                },
                "items": {
                    "description": "菜单项",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/menu.Item"
                    }
                }
            }
        },
        "openai.ChatCompletionMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "name": {
                    "description": "This property isn't in the official documentation, but it's in\nthe documentation for the official library for python:\n- https://github.com/openai/openai-python/blob/main/chatml.md\n- https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb",
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "openai.ImageRequest": {
            "type": "object",
            "properties": {
                "n": {
                    "type": "integer"
                },
                "prompt": {
                    "type": "string"
                },
                "response_format": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "openaiapi.ChatCompletionRequest": {
            "type": "object",
            "properties": {
                "frequency_penalty": {
                    "type": "number"
                },
                "max_tokens": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/openai.ChatCompletionMessage"
                    }
                },
                "model": {
                    "type": "string"
                },
                "role": {
                    "description": "角色",
                    "type": "string"
                },
                "stream": {
                    "type": "boolean"
                },
                "temperature": {
                    "type": "number"
                }
            }
        },
        "payapi.PreCreateRequest": {
            "type": "object",
            "required": [
                "productType"
            ],
            "properties": {
                "payType": {
                    "description": "支付类型，目前只支持alipay",
                    "type": "string",
                    "default": "alipay"
                },
                "productType": {
                    "description": "商品类型，1-10元,2-30元,3-100元",
                    "type": "integer"
                }
            }
        },
        "payapi.PreCreateResponse": {
            "type": "object",
            "properties": {
                "orderId": {
                    "description": "订单id",
                    "type": "string"
                },
                "qrCode": {
                    "description": "二维码串",
                    "type": "string"
                }
            }
        },
        "user.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "newPassword",
                "subjectName",
                "verificationCode"
            ],
            "properties": {
                "newPassword": {
                    "type": "string"
                },
                "subjectName": {
                    "type": "string"
                },
                "subjectType": {
                    "description": "可选字段，默认为userapi.ChangePasswordMailCode",
                    "type": "integer",
                    "default": 101
                },
                "verificationCode": {
                    "type": "string"
                }
            }
        },
        "user.ChatConfig": {
            "type": "object",
            "properties": {
                "frequencyPenalty": {
                    "description": "话题新鲜度,-2.0-2.0,默认为0",
                    "type": "number",
                    "default": 0
                },
                "model": {
                    "description": "模型",
                    "type": "string"
                },
                "temperature": {
                    "description": "随机性0-2,默认为1",
                    "type": "number",
                    "default": 1
                }
            }
        },
        "user.CustomConfig": {
            "type": "object",
            "properties": {
                "chatConfig": {
                    "description": "聊天配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.ChatConfig"
                        }
                    ]
                },
                "imageConfig": {
                    "description": "图片配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.ImageConfig"
                        }
                    ]
                }
            }
        },
        "user.FeedbackRequest": {
            "type": "object",
            "required": [
                "content",
                "feedbackType"
            ],
            "properties": {
                "content": {
                    "description": "反馈内容",
                    "type": "string"
                },
                "feedbackType": {
                    "description": "反馈类型: 1-问题反馈 2-功能建议 3-咨询 4-其他",
                    "type": "integer"
                }
            }
        },
        "user.ImageConfig": {
            "type": "object",
            "properties": {
                "n": {
                    "description": "返回几张图，默认1张",
                    "type": "integer",
                    "default": 1
                },
                "size": {
                    "description": "图片大小,256x256/512x512/1024x1024",
                    "type": "string"
                }
            }
        },
        "user.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "type": {
                    "description": "可选字段，默认为email",
                    "type": "string",
                    "default": "email"
                }
            }
        },
        "user.ProfileRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "customConfig": {
                    "description": "自定义配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.CustomConfig"
                        }
                    ]
                },
                "nickName": {
                    "description": "昵称",
                    "type": "string"
                }
            }
        },
        "user.ProfileResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "integral": {
                    "description": "用户当前积分",
                    "type": "integer"
                },
                "inviteCode": {
                    "description": "邀请码",
                    "type": "string"
                },
                "nickName": {
                    "description": "昵称",
                    "type": "string"
                },
                "vipUser": {
                    "description": "是否是vip用户",
                    "type": "boolean"
                }
            }
        },
        "user.RegisterRequest": {
            "type": "object",
            "required": [
                "code",
                "email",
                "password"
            ],
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "inviteCode": {
                    "description": "邀请码",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "type": {
                    "description": "可选字段，默认为email",
                    "type": "string",
                    "default": "email"
                }
            }
        },
        "user.SendPasswordVerificationCodeRequest": {
            "type": "object",
            "required": [
                "subjectName"
            ],
            "properties": {
                "subjectName": {
                    "type": "string"
                },
                "subjectType": {
                    "description": "可选字段，默认为userapi.ChangePasswordMailCode",
                    "type": "integer",
                    "default": 101
                }
            }
        },
        "user.SendVerificationCodeRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "type": {
                    "description": "可选字段，默认为email",
                    "type": "string",
                    "default": "email"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
