definitions:
  integral.BatchGenerateKeyRequest:
    properties:
      count:
        default: 10
        type: integer
      type:
        default: 1
        description: 1代表100积分，2代表500积分，3代表1000积分
        type: integer
    type: object
  integral.RechargeRequest:
    properties:
      key:
        type: string
    required:
    - key
    type: object
  integral.RecordRequest:
    properties:
      model:
        description: 使用模型
        type: string
      size:
        description: 大小，chat为字数，image为尺寸，audio为时长(分钟)
        type: integer
      type:
        description: 计费类型，chat/image/audio
        type: string
    required:
    - model
    - size
    - type
    type: object
  openai.ChatCompletionMessage:
    properties:
      content:
        type: string
      name:
        description: |-
          This property isn't in the official documentation, but it's in
          the documentation for the official library for python:
          - https://github.com/openai/openai-python/blob/main/chatml.md
          - https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb
        type: string
      role:
        type: string
    type: object
  openai.ChatCompletionRequest:
    properties:
      frequency_penalty:
        type: number
      logit_bias:
        additionalProperties:
          type: integer
        type: object
      max_tokens:
        type: integer
      messages:
        items:
          $ref: '#/definitions/openai.ChatCompletionMessage'
        type: array
      model:
        type: string
      "n":
        type: integer
      presence_penalty:
        type: number
      stop:
        items:
          type: string
        type: array
      stream:
        type: boolean
      temperature:
        type: number
      top_p:
        type: number
      user:
        type: string
    type: object
  openai.ImageRequest:
    properties:
      "n":
        type: integer
      prompt:
        type: string
      response_format:
        type: string
      size:
        type: string
      user:
        type: string
    type: object
  user.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
      type:
        default: email
        description: 可选字段，默认为email
        type: string
    required:
    - email
    - password
    type: object
  user.ProfileRequest:
    properties:
      avatar:
        description: 头像
        type: string
      nick_name:
        description: 昵称
        type: string
    type: object
  user.ProfileResponse:
    properties:
      avatar:
        description: 头像
        type: string
      email:
        description: 邮箱
        type: string
      integral:
        description: 用户当前积分
        type: integer
      invite_code:
        description: 邀请码
        type: string
      nick_name:
        description: 昵称
        type: string
    type: object
  user.RegisterRequest:
    properties:
      code:
        description: 验证码
        type: string
      email:
        description: 邮箱
        type: string
      invite_code:
        description: 邀请码
        type: string
      password:
        description: 密码
        type: string
      type:
        default: email
        description: 可选字段，默认为email
        type: string
    required:
    - code
    - email
    - password
    type: object
  user.SendVerificationCodeRequest:
    properties:
      email:
        type: string
      type:
        default: email
        description: 可选字段，默认为email
        type: string
    required:
    - email
    type: object
info:
  contact: {}
paths:
  /api/v1/integral/generate_key:
    post:
      parameters:
      - description: 生成key的请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/integral.BatchGenerateKeyRequest'
      responses: {}
      summary: 生成积分充值密钥并发送到指定邮箱
      tags:
      - 积分相关接口
  /api/v1/integral/recharge:
    post:
      parameters:
      - description: 充值请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/integral.RechargeRequest'
      responses: {}
      summary: 充值
      tags:
      - 积分相关接口
  /api/v1/integral/record:
    post:
      parameters:
      - description: 请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/integral.RecordRequest'
      responses: {}
      summary: 记录
      tags:
      - 积分相关接口
  /api/v1/openai/v1/audio:
    post:
      parameters:
      - description: 音频文件
        in: formData
        name: audio
        required: true
        type: file
      - description: model
        in: query
        name: model
        type: string
      - description: language
        in: query
        name: language
        type: string
      - description: prompt
        in: query
        name: prompt
        type: string
      - description: temperature
        in: query
        name: temperature
        type: number
      responses: {}
      summary: 音频转文字
      tags:
      - 代理OpenAI相关接口
  /api/v1/openai/v1/chat/completions:
    post:
      parameters:
      - description: openai请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/openai.ChatCompletionRequest'
      responses: {}
      summary: 对话
      tags:
      - 代理OpenAI相关接口
  /api/v1/openai/v1/image:
    post:
      parameters:
      - description: openai请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/openai.ImageRequest'
      responses: {}
      summary: 生成图片
      tags:
      - 代理OpenAI相关接口
  /api/v1/user/login:
    post:
      parameters:
      - description: 登录请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/user.LoginRequest'
      responses:
        "200":
          description: 返回token
          schema:
            type: string
      summary: 登录
      tags:
      - 用户相关接口
  /api/v1/user/profile:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ProfileResponse'
      summary: 获取用户信息
      tags:
      - 用户相关接口
    post:
      parameters:
      - description: 用户信息
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/user.ProfileRequest'
      responses: {}
      summary: 修改用户信息
      tags:
      - 用户相关接口
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/user.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 返回token
          schema:
            type: string
      summary: 用户注册
      tags:
      - 用户相关接口
  /api/v1/user/verify/send_code:
    post:
      parameters:
      - description: 发送验证码请求参数(默认为email)
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/user.SendVerificationCodeRequest'
      responses: {}
      summary: 发送验证码
      tags:
      - 用户相关接口
swagger: "2.0"
